from __future__ import annotations

import os
import smtplib
from datetime import datetime
from email.message import EmailMessage
from pathlib import Path
from typing import Any, Mapping

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = os.getenv("GMAIL_USER", "")
SMTP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")


def send_claim_email(
    recipient_email: str,
    employee_name: str,
    claim: Mapping[str, Any],
    pdf_file_path: str | Path,
) -> None:
    if not SMTP_USER or not SMTP_PASSWORD:
        raise RuntimeError(
            "Email sending is not configured. Set GMAIL_USER and GMAIL_APP_PASSWORD."
        )

    pdf_path = Path(pdf_file_path)
    if not pdf_path.exists():
        raise FileNotFoundError(f"Claim PDF not found: {pdf_path}")

    date_submitted = datetime.now().strftime("%d/%m/%Y")
    treatment = str(claim.get("claim_type", "Claim")).strip() or "Claim"
    message = EmailMessage()
    message["Subject"] = f"Claim Request — {treatment} — {date_submitted}"
    message["From"] = SMTP_USER
    message["To"] = recipient_email
    message.set_content(
        "\n".join(
            [
                f"Hello {employee_name},",
                "",
                "Your health insurance claim summary is attached as a PDF.",
                "Please keep this email for your records and forward the claim to your insurer.",
                "Attach your original receipt or invoice when submitting the claim.",
                "",
                "Summary:",
                f"- Treatment: {claim.get('claim_type', 'Not provided')}",
                f"- Date of service: {claim.get('date_of_service', 'Not provided')}",
                f"- Amount: {_format_currency(claim.get('amount_eur'))}",
                "",
                "Generated by AI Health Insurance Assistant.",
            ]
        )
    )

    message.add_attachment(
        pdf_path.read_bytes(),
        maintype="application",
        subtype="pdf",
        filename=pdf_path.name,
    )

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.ehlo()
        smtp.login(SMTP_USER, SMTP_PASSWORD)
        smtp.send_message(message)


def infer_employee_name(email_address: str) -> str:
    local_part = email_address.split("@", 1)[0].strip()
    cleaned = local_part.replace(".", " ").replace("_", " ").replace("-", " ").strip()
    return " ".join(segment.capitalize() for segment in cleaned.split()) or "Employee"


def _format_currency(value: Any) -> str:
    if value is None or value == "":
        return "Not provided"
    return f"EUR {float(value):.2f}"
