from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Mapping

from fpdf import FPDF

from config import GENERATED_CLAIMS_DIR


class ClaimPDF(FPDF):
    def footer(self) -> None:
        self.set_y(-18)
        self.set_font("Helvetica", size=9)
        self.set_text_color(90, 99, 94)
        self.multi_cell(
            0,
            5,
            (
                "Generated by AI Health Insurance Assistant. "
                "Attach original receipt when submitting to insurer."
            ),
            align="C",
        )


def generate_claim_pdf(claim: Mapping[str, Any]) -> Path:
    GENERATED_CLAIMS_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = GENERATED_CLAIMS_DIR / f"claim_{timestamp}.pdf"

    pdf = ClaimPDF()
    pdf.set_auto_page_break(auto=True, margin=24)
    pdf.add_page()

    pdf.set_fill_color(24, 62, 52)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", style="B", size=18)
    pdf.cell(0, 14, "4D Health Insurance — Claim Request", new_x="LMARGIN", new_y="NEXT", fill=True)

    pdf.ln(5)
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(45, 55, 48)
    pdf.cell(
        0,
        8,
        f"Date submitted: {datetime.now().strftime('%d/%m/%Y')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(
        0,
        8,
        f"Selected plan: {claim.get('plan_id', 'Not provided')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    pdf.ln(4)
    _render_claim_table(
        pdf,
        [
            ("Treatment", str(claim.get("claim_type", "Not provided"))),
            ("Date of service", str(claim.get("date_of_service", "Not provided"))),
            ("Amount", _format_currency(claim.get("amount_eur"))),
            ("Receipt attached", _format_bool(claim.get("has_receipt"))),
            ("Policy covered", _format_bool(claim.get("policy_covered"))),
            ("Email recipient", str(claim.get("email_address", "Not provided"))),
        ],
    )

    pdf.ln(5)
    _render_detail_block(
        pdf,
        "Coverage details",
        str(claim.get("coverage_details", "Not provided")),
    )
    pdf.ln(3)
    _render_detail_block(
        pdf,
        "Policy source",
        str(claim.get("coverage_source", "Not provided")),
    )

    if claim.get("amount_limit_label"):
        pdf.ln(3)
        _render_detail_block(
            pdf,
            "Benefit limit note",
            (
                f"Plan limit identified: {claim.get('amount_limit_label')}. "
                f"Calculated maximum reimbursement reference: {_format_currency(claim.get('amount_limit_eur'))}."
            ),
        )

    pdf.output(str(output_path))
    return output_path


def _render_claim_table(pdf: FPDF, rows: list[tuple[str, str]]) -> None:
    label_width = 56
    value_width = pdf.w - pdf.l_margin - pdf.r_margin - label_width

    pdf.set_draw_color(210, 217, 212)
    pdf.set_fill_color(243, 245, 242)
    pdf.set_text_color(36, 43, 39)

    for label, value in rows:
        value_text = _normalize_value(value)
        row_height = max(9, 5 * (pdf.get_string_width(value_text) / max(value_width - 4, 1) // 1 + 1))
        pdf.set_font("Helvetica", style="B", size=10)
        pdf.multi_cell(
            label_width,
            row_height,
            _normalize_value(label),
            border=1,
            fill=True,
            new_x="RIGHT",
            new_y="TOP",
        )
        pdf.set_font("Helvetica", size=10)
        pdf.multi_cell(
            value_width,
            row_height,
            value_text,
            border=1,
            new_x="LMARGIN",
            new_y="NEXT",
        )


def _render_detail_block(pdf: FPDF, title: str, value: str) -> None:
    pdf.set_font("Helvetica", style="B", size=11)
    pdf.set_text_color(24, 62, 52)
    pdf.cell(0, 7, _normalize_value(title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(45, 55, 48)
    pdf.multi_cell(
        0,
        6,
        _normalize_value(value),
        border=1,
        fill=False,
        padding=2,
    )


def _format_currency(value: Any) -> str:
    if value is None or value == "":
        return "Not provided"
    return f"EUR {float(value):.2f}"


def _format_bool(value: Any) -> str:
    if value is None:
        return "Not provided"
    return "Yes" if bool(value) else "No"


def _normalize_value(value: str) -> str:
    return str(value).replace("\u20ac", "EUR ").replace("\u2014", "-")
